name: "Test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  macOS:
    strategy:
      fail-fast: false
      matrix:
        xcode: ["15.0.1"]
        include:
          - xcode: "15.0.1"
            macos: macos-13
    runs-on: ${{ matrix.macos }}
    name: macOS
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app; swift -version
      - name: Get Swift Version
        id: get-swift-version
        run: |
          echo "version=$(swift -version | head -n 1 | sed s/,// )" >> "$GITHUB_OUTPUT"
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            .build/artifacts
            .build/checkouts
            .build/repositories
          key: ${{ runner.os }}-dependencies-${{ matrix.xcode }}-${{ hashFiles('./Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-${{ matrix.xcode }}-${{ hashFiles('./Package.resolved') }}
            ${{ runner.os }}-dependencies-${{ matrix.xcode }}-
      - name: Test
        run: swift test
  linux:
    strategy:
      fail-fast: false
      matrix:
        swift: ["5.9"]
        include:
          - swift: "5.9"
            container: "swift:5.9"
            cache-version: 1
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    name: Linux
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Swift Version
        id: get-swift-version
        run: |
          echo "version=$(swift -version | head -n 1 | sed s/,// )" >> "$GITHUB_OUTPUT"
        shell: bash
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            .build/artifacts
            .build/checkouts
            .build/repositories
          key: ${{ matrix.cache-version }}-${{ runner.os }}-${{ steps.get-swift-version.outputs.version }}}-spm-deps-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ matrix.cache-version }}-${{ runner.os }}-${{ steps.get-swift-version.outputs.version }}-spm-deps-
      - name: Test
        run: swift test
